//************************************************
//  FILE        :pwm_by_pwmlib_with_sync.ino
//  DATE        :2026/01/20
//  DESCRIPTION :PWM output by pwm.h library with synchronization
//  BOARD TYPE  :UNO R4 MINIMA
//  AUTHER      :inteGN
//************************************************
/*
D3ピンとD6ピンにPWM信号を出力します。

最初、pwmD3.begin()とpwmD6.begin()で2つのPWM信号が生成されます。
その2つの立ち上がりエッジの間には顕著なタイムラグがありますが、
これは20kHzのPWM周期の中でbegin()が異なるタイミングで実行されたためです。

20秒後、GPT1のオーバーフローイベントでGPT0がクリアされるよう
イベントリンクが設定されます。2つのPWM信号の立ち上がりエッジは同期しますが、
わずかなラグが残ります。

さらに20秒後、2番目のイベントリンクが設定され、GPT0とGPT1の両方が
GPT6のオーバーフローイベントによってクリアされます。その結果、両方の
PWM信号の立ち上がりエッジが完全に同期します。

This program outputs PWM signals on pins D3 and D6.

At first, two PWM signals are generated by pwmD3.begin() and pwmD6.begin().
But a noticeable time lag appears between their rising edges because the
begin() calls are executed at different moments relative to the 20 kHz PWM cycle.

After 20 seconds, an event-link is configured so that GPT0 is cleared by the
overflow event of GPT1. The rising edges of the two PWM signals become synchronized,
although a slight residual lag still remains.

After another 20 seconds, a second event-link is configured so that both GPT0
and GPT1 are cleared by the overflow event of GPT6. As a result, the rising
edges of both PWM signals become fully synchronized.
*/


//// Includes
#include <Arduino.h>
#include "FspLinkIrq.h"
#include "FspTimer.h"
#include "pwm.h"

//// Grobals
FspLinkIrq elcLink;
FspTimer  timer6;
PwmOut    pwmD3(D3);                        //Arduino D3 pin / RA4M1 P104 GPT1_B
PwmOut    pwmD6(D6);                        //Arduino D6 pin / RA4M1 P106 GPT0_B
uint32_t  pwm_reriod = 2400;
uint32_t  pwm_count0 =  800;


//// Setup function
void setup() {
  pwmD3.begin(pwm_reriod, pwm_count0, true, TIMER_SOURCE_DIV_1);    //RA4M1 P104 GPT1_B
  pwmD6.begin(pwm_reriod, pwm_count0, true, TIMER_SOURCE_DIV_1);    //RA4M1 P106 GPT0_B
  timer6.begin(TIMER_MODE_PERIODIC, GPT_TIMER, 6, pwm_reriod, pwm_count0, TIMER_SOURCE_DIV_1);
  timer6.open();
  timer6.start();                                                   //GPT6 set and start

  delay(20000);

//GPT0 clear by GPT1 overflow thru ELC_GPT_A
  elcLink.linkGPTimerIrq(1, LINK_GPT_OVERFLOW, ELC_PERIPHERAL_GPT_A);
  R_GPT0->GTCSR_b.CSELCA = 1;               //GPT0 clear by ELC_GPT_A event

  delay(20000);

//GPT0 and GPT1 clear by GPT6 overflow thru ELC_GPT_A
  elcLink.linkGPTimerIrq(6, LINK_GPT_OVERFLOW, ELC_PERIPHERAL_GPT_A);
  R_GPT1->GTCSR_b.CSELCA = 1;               //GPT1 clear by ELC_GPT_A event, GPT0 clear is already set
}

//// Loop function
void loop() {
// nothing to do
  delayMicroseconds(10);
}


